name: Deploy .NET API to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Publish API
      run: dotnet publish -c Release -o ./publish

    - name: Deploy to EC2 via SSH
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "./publish/*"
        target: "/home/ubuntu/my-api"
        strip_components: 1

    - name: Start/Restart Application on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/my-api
          pm2 describe MyWebApi > /dev/null
          if [ $? -eq 0 ]; then
            pm2 restart MyWebApi
          else
            pm2 start "dotnet MyWebApi.dll --urls=http://localhost:5000" --name "MyWebApi"
          fi
          pm2 save